config/routes.rb
Crm::Application.routes.draw do

  resources :engagements

  resources :groups do
    resources :contacts do
      resources :engagements
    end
  end

  get "home/index"
  get "home/about"
  get "groups/:id/join" => 'groups#join', as: :join_group
  get "groups/:id/members" => 'groups#members', as: :group_members
  get "groups/:id/members/remove/:member_id" => 'groups#remove_member', as: :group_remove_member
  get "groups/:id/leave" => 'groups#leave', as: :leave_group
  get "groups/:id/join_complete" => 'groups#join_complete', as: :join_group_complete
  get "mygroups" => 'groups#mygroups', as: :my_groups
  get "groups/:id/tags/:tag" => 'groups#tags', as: :group_tag
  devise_for :users, :path => ''

root 'home#index'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  
  has_and_belongs_to_many :users, :join_table => :members
  default_scope order('name')
  
  belongs_to :creator, class_name: "User", foreign_key: :user_id
  
  validates_presence_of :name, :password
  validates_uniqueness_of :name
  validates_length_of :name, :minimum => 3, :maximum => 80
  validates_length_of :password, :minimum => 6, :maximum => 18
  has_many :contacts, :dependent => :destroy
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def should_generate_new_friendly_id?
      new_record?
    end
  
  def self.search(search)
      if search
        where('lower(name) LIKE ?', "%#{search}%")
      else
        scoped
      end
    end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join, :join_complete, :leave, :members, :remove_member, :tags]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :join, :join_complete, :leave, :members, :remove_member, :mygroups, :tags]
  before_action :check_group_admin_controller, only: [:edit, :update, :destroy, :members, :remove_member, :tags]

  # GET /groups
  # GET /groups.json
  def index
    if params[:search]
    @groups = Group.search((params[:search]).to_s.downcase)
   end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    if @group.users.include?(current_user) || @group.creator == current_user
      @contacts = @group.contacts.search((params[:search]).to_s.downcase)
    else
    redirect_to join_group_path  
    end
  end
  
  def tags
     if @group.users.include?(current_user) || @group.creator == current_user
    @contacts = @group.contacts.tagged_with(params[:tag].to_s)
    else
    redirect_to join_group_path  
    end
  end
  
  def mygroups
    @belong_groups = current_user.groups.uniq
    @groups = current_user.owned_groups
    #.paginate(:per_page => 10, :page => params[:page])
  end
  
  def join
    if (@group.users.include?(current_user)) || (@group.creator == current_user)
       flash[:notice] = "You are already a member of this group."
       redirect_to groups_url
    end
  end
  
  def members
     @members = @group.users
  end
  
  def remove_member
    usr = User.find(params[:member_id])
    if @group.users.include?(usr)
      @group.users.delete(usr)
       flash[:notice] = "Successfuly removed user from group."
       redirect_to group_members_path
     else
       flash[:notice] = "Not a member of this group."
       redirect_to groups_url
     end
  end
  
  def leave
    if @group.creator == current_user
      flash[:notice] = "You are the owner of this group. To remove this group, delete it."
      redirect_to groups_url and return
    end
      if @group.users.include?(current_user)
        @group.users.delete(current_user)
         flash[:notice] = "Successfuly left group."
         redirect_to groups_url
       else
         flash[:notice] = "Not a member of this group."
         redirect_to groups_url
       end
  end
  
  
def join_complete
if current_user
if @group.password == params[:pass]
  @group.users << current_user
  else
    flash[:notice] = "Wrong password."
    redirect_to groups_url and return
  end
else
  flash[:notice] = "Log in please."
  redirect_to groups_url and return
end
redirect_to groups_url and return
end
  
  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    if current_user
      @group.user_id = current_user.id
    end
    
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :password, :search)
    end
    
    def check_group_admin_controller
      
      unless check_group_admin?
       flash[:notice] = "You are not the admin of this group."
       redirect_to groups_path
     end
    end
    
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_contacts.html.erb
<table class="table">
<% @contacts.each do |contact| %>
  <tr>
    <td><%= link_to contact.name, [contact.group, contact] %></td>
    <td><%= "Added by #{User.find_by_id(contact.added_by).email}" %></td>
    <td><%= contact.email_id %></td>
    <%if contact.phones %><td>
	<% contact.phones.find(:all, :limit =>1).each do |cp| %>
	<%= cp.phone_no%>
	<%end%>
	</td><%end%>
	<td><%= link_to 'Show', [contact.group, contact]%></td>
    <td><%= link_to 'Edit', edit_group_contact_path(contact.group, contact) %></td>
    <td><%= link_to 'Destroy', [contact.group, contact], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :name, :required => true, label: 'Group Name', :autofocus => true, input_html: {:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.input :password, :required => true, input_html: {:class => 'form-control'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create Group" %>
  </div>


<% end %>

app/views/groups/_groups.html.erb
<table class="table">



  <tbody>
<%if @groups%>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td><%= group.users.count + 1 %></td>

        <%if group.creator == current_user %><td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %></td><%end%>
      </tr>
    <% end %>
<%end%>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="col-md-6">
	<div class="page-header">
		<h1>Editing group</h1>
	</div>

	<%= render 'form' %>

</div>

<div class="col-md-6">
	<div class="page-header">
		<h1>Add your groups to the best customer management tool to grace the interwebs</h1>
	</div>
	<%= link_to 'Show', @group %> |
	<%= link_to 'Back', groups_path %>
</div>

app/views/groups/index.html.erb
<h1>Find a group</h1>


<%= form_tag groups_path , :method => 'get', :id => "gs" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
  </p>
<% end %>

<div class="group_toggler">
	

<div id="groups">
<%= render 'groups'%>
</div>


<br>

</div>

<%= link_to "Create a group, it's free!", new_group_path %>

app/views/groups/index.js.erb
$('#groups').html('<%= escape_javascript(render("groups")) %>');

app/views/groups/join.html.erb
<br/>Enter pass?
<%= form_tag join_group_complete_path, :method => 'get', :id => "gs" do %>
  <p>
    <%= text_field_tag :pass, params[:pass] %>
    <%= submit_tag "Ok", :name => nil %>
  </p>
<% end %>

app/views/groups/members.html.erb
<table>
<tr><td>Admin: <%= @group.creator.email %></td></tr>
<% @members.each do |member| %>
<tr>
	<td><%=member.email%> &nbsp;&nbsp;&nbsp;&nbsp; <%=link_to "Remove Member", group_remove_member_path(:member_id => member.id)%></td> 
   
	</tr>
	<%end%>
	</table>

app/views/groups/mygroups.html.erb
<h1>Groups I own</h1>
<div id="groups1">
<%= render 'groups'%>
</div>


<div id="groups2">
	<h1>Groups I belong to</h1>
	<table class="table">



	  <tbody>
	<%if @belong_groups%>
	    <% @belong_groups.each do |group| %>
	      <tr>
	        <td><%= link_to group.name, group %></td>
	        <td><%= group.users.count + 1 %></td>

	        <%if group.creator == current_user %><td><%= link_to 'Edit', edit_group_path(group) %></td>
	        <td><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %></td><%end%>
	      </tr>
	    <% end %>
	<%end%>
	  </tbody>
	</table>
</div>
<br>



<%= link_to "Create a group, it's free!", new_group_path %> | 
<%= link_to "Back to search", groups_path%>
</div>

app/views/groups/new.html.erb
<div class="col-md-6">
	<div class="page-header">
		<h1>Create New Group</h1>
	</div>

	<%= render 'form' %>

</div>

<div class="col-md-6">
	<div class="page-header">
		<h1>Add your groups to the best customer management tool to grace the interwebs</h1>
	</div>
	<%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
<% content_for(:side_bar) do %>
    <%= render :partial => "/shared/sidebar" %>
<% end %>


<h2> Contacts </h2>

<%= form_tag group_path(@group) , :method => 'get', :id => "gs2" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
   
  </p>
<% end %>

 <div id="contacts"><%= render 'contacts' %></div>

<%= link_to 'New', new_group_contact_path(@group)%> |
<% if check_group_admin? %>
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Destroy this group', group_path(@group), method: :delete, :message => "This will delete everything. Ok?" %> |
<%end%>
<%= link_to 'Back', groups_path %>

app/views/groups/show.js.erb
$('#contacts').html('<%= escape_javascript(render("contacts")) %>');

app/views/groups/tags.html.erb
<% content_for(:side_bar) do %>
    <%= render :partial => "/shared/sidebar" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Added by</th>
      <th>Email</th>
      <th>Facebook</th>
      <th>Skype</th>
      <th>Twitter</th>
      <th>Engagement count</th>
      <th>Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= User.find(contact.added_by).email %></td>
        <td><%= contact.email_id %></td>
        <td><%= contact.facebook_id %></td>
        <td><%= contact.skype_id %></td>
        <td><%= contact.twitter_id %></td>
        <td><%= contact.engagements_count %></td>
        <td><%= raw contact.tag_list.map { |t| link_to t, group_tag_path(@group, t) }.join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>