config/routes.rb
Crm::Application.routes.draw do

  resources :engagements

  resources :groups do
    resources :contacts do
      resources :engagements
    end
  end

  get "home/index"
  get "home/about"
  get "groups/:id/join" => 'groups#join', as: :join_group
  get "groups/:id/members" => 'groups#members', as: :group_members
  get "groups/:id/members/remove/:member_id" => 'groups#remove_member', as: :group_remove_member
  get "groups/:id/leave" => 'groups#leave', as: :leave_group
  get "groups/:id/join_complete" => 'groups#join_complete', as: :join_group_complete
  get "mygroups" => 'groups#mygroups', as: :my_groups
  get "groups/:id/tags/:tag" => 'groups#tags', as: :group_tag
  devise_for :users, :path => ''

root 'home#index'

  

end

app/models/engagement.rb
class Engagement < ActiveRecord::Base
  belongs_to :contact, :counter_cache => true
end

app/controllers/engagements_controller.rb
class EngagementsController < ApplicationController
  before_action :set_engagement, only: [:destroy]
   before_action :authenticate_user!
  # GET /engagements
  # GET /engagements.json
  # GET /engagements/new
  # POST /engagements
  # POST /engagements.json
  def create
    check_member_or_admin_of_group?
    @engagement = Engagement.new(engagement_params)
    @engagement.contact_id = Contact.friendly.find(params[:contact_id]).id
   #@engagement.contact_id = params[:contactid]
    respond_to do |format|
      if @engagement.save
        format.html { redirect_to request.referer, notice: 'Engagement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @engagement }
      else
        format.html { render action: 'new' }
        format.json { render json: @engagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engagements/1
  # PATCH/PUT /engagements/1.json

  # DELETE /engagements/1
  # DELETE /engagements/1.json
  def destroy
    check_member_or_admin_of_group?
    @engagement.destroy
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engagement
      @engagement = Engagement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engagement_params
      params.require(:engagement).permit(:description, :engage_time, :engage_date)
    end
    
      def check_member_or_admin_of_group?
        if (params[:group_id])
          @group = Group.friendly.find(params[:group_id])
        if @group.users.include?(current_user) || @group.creator == current_user
          return true
        else
          redirect_to join_group_path(@group) and return false
      end
    end
    end
end

app/helpers/engagements_helper.rb
module EngagementsHelper
	def datepassed?(engagement)
		if engagement.engage_date > Date.current
			return "coming"
		elsif engagement.engage_date == Date.current
			return "today"
		else return "past"
		end
	end
end

app/views/engagements/_form.html.erb
<%= simple_form_for(@engagement) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :description, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :engage_time, input_html: {class: 'form-control engagetime'} %>
  </div>
  <div class="form-group">
    <%= f.input :engage_date, input_html: {class: 'form-control engagedate'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/engagements/edit.html.erb
<div class="col-md-6">
	<div class="page-header">
		<h1>Edit Engagement</h1>
	</div>

<%= render 'form' %>

<%= link_to 'Show', @engagement %> |
<%= link_to 'Back', engagements_path %>

</div>

<div class="col-md-6">
	<div class="page-header">
		<h1>Get ready to join the best customer management tool to grace the interwebs</h1>
	</div>
</div>

app/views/engagements/index.html.erb
<h1>Listing engagements</h1>

<table class="table engagements">
  <thead>
    <tr>
      <th>Description</th>
      <th>Engage time</th>
      <th>Engage date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @engagements.each do |engagement| %>
      <tr class="<%= datepassed?(engagement) %>">
        <td><%= engagement.description %></td>
        <td><%= engagement.engage_time.strftime("%I:%M%p") %></td>
        <td><%= engagement.engage_date %></td>
        <td><%= link_to 'Show', engagement %></td>
        <td><%= link_to 'Edit', edit_engagement_path(engagement) %></td>
        <td><%= link_to 'Destroy', engagement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engagement', new_engagement_path %>

app/views/engagements/new.html.erb
<div class="col-md-6">
	<div class="page-header">
		<h1>New Engagement</h1>
	</div>

<%= render 'form' %>

<%= link_to 'Back', engagements_path %>
</div>

<div class="col-md-6">
	<div class="page-header">
		<h1>Get ready to join the best customer management tool to grace the interwebs</h1>
	</div>
</div>

app/views/engagements/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @engagement.description %>
</p>

<p>
  <strong>Engage time:</strong>
  <%= @engagement.engage_time %>
</p>

<p>
  <strong>Engage date:</strong>
  <%= @engagement.engage_date %>
</p>

<%= link_to 'Edit', edit_engagement_path(@engagement) %> |
<%= link_to 'Back', engagements_path %>