config/routes.rb
Crm::Application.routes.draw do

  resources :engagements

  resources :groups do
    resources :contacts do
      resources :engagements
    end
  end

  get "home/index"
  get "home/about"
  get "groups/:id/join" => 'groups#join', as: :join_group
  get "groups/:id/members" => 'groups#members', as: :group_members
  get "groups/:id/members/remove/:member_id" => 'groups#remove_member', as: :group_remove_member
  get "groups/:id/leave" => 'groups#leave', as: :leave_group
  get "groups/:id/join_complete" => 'groups#join_complete', as: :join_group_complete
  get "mygroups" => 'groups#mygroups', as: :my_groups
  get "groups/:id/tags/:tag" => 'groups#tags', as: :group_tag
  devise_for :users, :path => ''

root 'home#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar-wrapper">
      

	    <div class="navbar navbar-inverse navbar-static-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <%=link_to "Tracr", root_url, { class: 'navbar-brand' } %>
	        </div>
	        <div class="navbar-collapse collapse">
	          <ul class="nav navbar-nav">
	            <%if user_signed_in?%>
					<li><%=link_to "My Groups", my_groups_path %></li>
				<%end%>
				<li><%=link_to "Groups", groups_path %></li>
				<%if user_signed_in?%>
					<li><%=link_to "Signed in as #{current_user.email}. Log Out?", destroy_user_session_path, method: :delete%></li>
				<%else%>
					<li><%=link_to "Sign in", new_user_session_path %></li>
					<li><%=link_to "Sign up", new_user_registration_path %></li>
				<%end%>
	            <!-- <li class="dropdown">
	              <a href="./Carousel Template for Bootstrap_files/Carousel Template for Bootstrap.html" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
	              <ul class="dropdown-menu">
	                <li><a href="./Carousel Template for Bootstrap_files/Carousel Template for Bootstrap.html">Action</a></li>
	                <li><a href="./Carousel Template for Bootstrap_files/Carousel Template for Bootstrap.html">Another action</a></li>
	                <li><a href="./Carousel Template for Bootstrap_files/Carousel Template for Bootstrap.html">Something else here</a></li>
	                <li class="divider"></li>
	                <li class="dropdown-header">Nav header</li>
	                <li><a href="./Carousel Template for Bootstrap_files/Carousel Template for Bootstrap.html">Separated link</a></li>
	                <li><a href="./Carousel Template for Bootstrap_files/Carousel Template for Bootstrap.html">One more separated link</a></li>
	              </ul>
	            </li> -->
	          </ul>
	        </div>
	      </div>
	    </div>

    </div>

    

<%if current_page?('/') %>
	<%= yield %>
<%else%>

	<div class="wrapper">

		<%if content_for(:side_bar)%>
			<div id="side-content" class="col-md-2">
			    <%= yield(:side_bar) %>
			</div>
		<%end%>

		<div <%if content_for(:side_bar)%>
				class="spl col-md-10"
			 <%else%>
			 	class="spl col-md-12"
			 <%end%>
				>
			<%if notice%><li class="alert alert-info"><%= notice %></li><%end%>
			<%if alert%><li class="alert alert-error"><%= alert %></li><%end%>
			<%= yield %>
		</div>
		
	</div>

<%end%>

</body>
</html>